spring.datasource.url=jdbc:mysql://autorack.proxy.rlwy.net:21110/railway
spring.datasource.username=root
spring.datasource.password=yBunqOALYQzCaQfKBKxMaEJkEADdnBjF

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8010